<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_show_months</name>
   <tag></tag>
   <elementGuidId>9dae1744-f6dd-4ff3-b427-7285e5d02970</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;scflightschedule&quot;]/div/span/div[1]/div/div/div[1]/div[2]/div/div/div[2]/div[2]/div/div/div[2]/div[1]/div[2]/div[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
