<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_show_years</name>
   <tag></tag>
   <elementGuidId>1503ac3d-d07e-41cf-9309-7f04dc934bfd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;scflightschedule&quot;]/div/span/div[1]/div/div/div[1]/div[2]/div/div/div[2]/div[2]/div/div/div[2]/div[1]/div[2]/div[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
