<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_Flight Schedule</name>
   <tag></tag>
   <elementGuidId>92c3fdec-6312-4d30-8c64-2b9ae0975e79</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='menu-item-1447']/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#menu-item-1447 > a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>9e4abd2b-8d90-4e6b-978d-556f952208ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://www.siacargo.com/e-services/flightschedule_public/</value>
      <webElementGuid>38394bbe-35ba-41a6-8811-80b4967e2084</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Flight Schedule</value>
      <webElementGuid>d1869be7-47e6-4788-86ef-720ba06757d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;menu-item-1447&quot;)/a[1]</value>
      <webElementGuid>6dcb0b20-4494-4560-9de2-d1581819b332</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='menu-item-1447']/a</value>
      <webElementGuid>5ce8ca43-eafd-43a6-8e7a-150e60cc2e3b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Flight Schedule')]</value>
      <webElementGuid>c381ba8b-f6e1-47e0-947b-ec55d971df61</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Valuable Cargo'])[1]/following::a[2]</value>
      <webElementGuid>55d59860-5f3b-4677-ab54-bd6e75f2e835</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Live Animals'])[1]/following::a[3]</value>
      <webElementGuid>1a0bb0ee-2209-4ab0-a468-3a1aa130e267</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tracking'])[1]/preceding::a[1]</value>
      <webElementGuid>1375e3d9-ed0e-4d26-9385-99cae5ab85f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='eTimetable'])[1]/preceding::a[2]</value>
      <webElementGuid>f9612835-5ca9-4831-a17e-19d7c7f7cb40</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Flight Schedule']/parent::*</value>
      <webElementGuid>4405e88e-b05c-4881-92b1-db770b51602c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://www.siacargo.com/e-services/flightschedule_public/')]</value>
      <webElementGuid>c4d9b98a-0a4e-44c8-9746-38be8ed8ca9e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[4]/ul/li/a</value>
      <webElementGuid>e05c6546-e921-4e33-a7e6-d6d993cf73ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://www.siacargo.com/e-services/flightschedule_public/' and (text() = 'Flight Schedule' or . = 'Flight Schedule')]</value>
      <webElementGuid>0ca961a1-2e37-4fb3-a602-a6b1ad700bca</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
