<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_Tracking</name>
   <tag></tag>
   <elementGuidId>f53599ad-8419-4295-82fc-1afa6b1431c2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='menu-item-2121']/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#menu-item-2121 > a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>62566f95-e3e9-4601-bdbc-55b311009cf8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://www.siacargo.com/e-services/quicksearch_public/?transId=</value>
      <webElementGuid>818794bc-2f93-466a-b1e6-ec820a294d96</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Tracking</value>
      <webElementGuid>9074e47d-6da1-4127-b8e9-9cfccde2f9eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;menu-item-2121&quot;)/a[1]</value>
      <webElementGuid>827c6902-61b1-46d0-a404-0cdd604d0396</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='menu-item-2121']/a</value>
      <webElementGuid>b4281288-804f-4b5d-91c4-94bffc1ac4d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Tracking')]</value>
      <webElementGuid>95afb042-c2d7-4433-b5db-6f0569c8e52d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Flight Schedule'])[1]/following::a[1]</value>
      <webElementGuid>8081947f-9cb4-43b3-b93b-80524ce2c61b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Valuable Cargo'])[1]/following::a[3]</value>
      <webElementGuid>4a0e4754-e16b-447c-9ea4-7180670bbd77</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='eTimetable'])[1]/preceding::a[1]</value>
      <webElementGuid>46dbb6e1-8b30-457f-9fc9-e2e3972232b4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='eAWB'])[1]/preceding::a[2]</value>
      <webElementGuid>f3c9ff59-1d26-404f-b8e0-243951e16a02</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Tracking']/parent::*</value>
      <webElementGuid>ceb0c902-6531-4e64-964a-954fd13829b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://www.siacargo.com/e-services/quicksearch_public/?transId=')]</value>
      <webElementGuid>6f02f794-3af3-4411-bcb6-c0fe06d6b320</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[4]/ul/li[2]/a</value>
      <webElementGuid>8c77ba0a-a97b-475b-a10c-2633e23d59ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://www.siacargo.com/e-services/quicksearch_public/?transId=' and (text() = 'Tracking' or . = 'Tracking')]</value>
      <webElementGuid>f084edc5-ed52-4280-a1e9-e183575b8cb4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
