<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_SEARCH</name>
   <tag></tag>
   <elementGuidId>a5143372-b946-4d07-b812-c075c23f3eb4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.theme-module_btn__Dp-TQ.index_sqpp-primary-download-btn__L16Sa.btn.btn-secondary</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>3272593c-3d09-4d03-9655-75b81e3c3ab7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>9825a865-2f72-41df-ba98-e20b2ddbac61</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>theme-module_btn__Dp-TQ index_sqpp-primary-download-btn__L16Sa btn btn-secondary</value>
      <webElementGuid>87121e00-51db-4e11-a040-28dfee0d4d83</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>SEARCH</value>
      <webElementGuid>2ed3e370-c7d2-443e-8ecb-20c869715cbc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;scflightschedule&quot;)/div[@class=&quot;FS-wrapper-container sqpp-master-container&quot;]/span[1]/div[1]/div[@class=&quot;flightSearch large-screen-size&quot;]/div[@class=&quot;flightSearchContainer&quot;]/div[@class=&quot;flightSearchFilterContainer&quot;]/div[@class=&quot;fsSearchActions&quot;]/span[@class=&quot;index_sqpp-primary-download-btn-container__FaCQe&quot;]/button[@class=&quot;theme-module_btn__Dp-TQ index_sqpp-primary-download-btn__L16Sa btn btn-secondary&quot;]</value>
      <webElementGuid>c1aed6a8-94af-4c9f-9af8-d837ad2a6399</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[2]</value>
      <webElementGuid>0b70a8a0-3b92-4281-a593-bf74b1cf2562</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//flight-schedule[@id='scflightschedule']/div/span/div/div/div/div[2]/div[2]/span/button</value>
      <webElementGuid>2337e538-935d-4578-95a2-012d82417139</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Reset / New Search'])[1]/preceding::button[1]</value>
      <webElementGuid>9dfdfc02-97e6-4358-b08f-89764d44b97b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Need an overview for a flight or route? Download eTimetable'])[1]/preceding::button[1]</value>
      <webElementGuid>2f76ec43-0e8e-4b13-96b6-f450d0f6c98b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='SEARCH']/parent::*</value>
      <webElementGuid>6754ae38-f003-4c3a-ac89-05265f9a1390</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/button</value>
      <webElementGuid>aff517a7-3386-4883-9971-7953ce155899</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'SEARCH' or . = 'SEARCH')]</value>
      <webElementGuid>d8d1b3ff-af0e-4575-8187-f19eb4d50fb6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
