<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_TRACK</name>
   <tag></tag>
   <elementGuidId>f04e5ca4-05b7-4536-9451-4622f7023c12</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@type='button']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.theme-module_btn__Dp-TQ.index_sqpp-primary-download-btn__L16Sa.btn.btn-secondary</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>b749c09a-cecf-453e-8c18-fc34c1f40b20</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>6b8d28ce-aa02-4516-a0b3-5fe54ee7d18f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>theme-module_btn__Dp-TQ index_sqpp-primary-download-btn__L16Sa btn btn-secondary</value>
      <webElementGuid>cbe51a41-9001-4f25-ac01-79f01c48f084</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>TRACK</value>
      <webElementGuid>4cb40188-789c-4a3d-9e57-cd1ccf722e98</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;scquicksearch&quot;)/div[@class=&quot;sqpp-quicksearch-wc-container sqpp-master-container&quot;]/div[1]/div[@class=&quot;sqpp-tracking-quicksearch-searchbar-container&quot;]/div[@class=&quot;sqpp-tracking-quicksearch-container&quot;]/div[@class=&quot;quicksearch-btn&quot;]/span[@class=&quot;index_sqpp-primary-download-btn-container__FaCQe&quot;]/button[@class=&quot;theme-module_btn__Dp-TQ index_sqpp-primary-download-btn__L16Sa btn btn-secondary&quot;]</value>
      <webElementGuid>df806b08-4235-4d75-9357-c5e49cea3dbd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@type='button']</value>
      <webElementGuid>85494962-1208-4962-8c93-d7725c965df1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tracking-quicksearch[@id='scquicksearch']/div/div/div/div/div/span/button</value>
      <webElementGuid>f4aadc24-1a06-40e5-9dd0-0190ed8a840b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tracking'])[2]/following::button[1]</value>
      <webElementGuid>1914235c-3ebb-4963-842d-35256ddf4609</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='e-Services'])[1]/following::button[1]</value>
      <webElementGuid>6bc5773f-6e94-4119-925c-b85fe90b7659</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='OUR PRODUCTS'])[1]/preceding::button[1]</value>
      <webElementGuid>25172bea-d8f3-41d4-9180-ab13fa653422</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/button</value>
      <webElementGuid>bd05cb07-f78d-4ce8-8b32-ef49defb8e2e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'TRACK' or . = 'TRACK')]</value>
      <webElementGuid>9788f0a8-64cc-4f90-8b07-4eba290cdab0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
