<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Tracking_awbInput</name>
   <tag></tag>
   <elementGuidId>e0c74fdf-7227-474b-bc5d-1349b555322e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='sqpp-tracking-quicksearch-awbfield-id']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#sqpp-tracking-quicksearch-awbfield-id</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>8b94857b-1db0-4a52-8ce2-215e59df5c77</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>sqpp-tracking-quicksearch-awbfield-id</value>
      <webElementGuid>a7551abf-5664-46fd-a03e-b7d852321974</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>7629ea36-6f67-465e-9021-05713b426ff5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>awbInput</value>
      <webElementGuid>11ae0c20-6716-4c29-94ab-6db06ae99838</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter AWB number separated by a comma. For example, 618-1234XXXX.</value>
      <webElementGuid>e1521998-9dc9-4b8a-b271-cd1923f4c10b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>6c9f7923-91fe-4af5-b795-a3457e47b0e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>theme-module_form-control__0sG2o sqpp-tracking-quicksearch-awbfield form-control</value>
      <webElementGuid>e695674f-5892-43fe-8d27-bc11cefc4622</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>3527abc4-374f-46f7-ba68-95d440cafeaa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;sqpp-tracking-quicksearch-awbfield-id&quot;)</value>
      <webElementGuid>4149932d-265a-40fb-9cbc-b2c2eb28b55c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='sqpp-tracking-quicksearch-awbfield-id']</value>
      <webElementGuid>71778a04-14f5-416d-bdb2-e12297ce8650</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tracking-quicksearch[@id='scquicksearch']/div/div/div/div/input</value>
      <webElementGuid>05975d27-70c8-4763-8212-0105d2b9823c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tracking-quicksearch/div/div/div/div/input</value>
      <webElementGuid>313ea991-1724-4a50-96fd-218d98c125ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'sqpp-tracking-quicksearch-awbfield-id' and @name = 'awbInput' and @placeholder = 'Enter AWB number separated by a comma. For example, 618-1234XXXX.' and @type = 'text']</value>
      <webElementGuid>35e3933e-1886-4a09-90b5-be61326d73b5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
