<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_departureDate</name>
   <tag></tag>
   <elementGuidId>4fca8520-624e-40d3-9a38-2a3ae37b1b66</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='fromFlightDate']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#fromFlightDate</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>64b6f613-c5e2-445f-85a6-2d9f280cfc5c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>66e4a231-3919-487d-b78d-76be0b78dd06</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>fromFlightDate</value>
      <webElementGuid>6dbf2bba-e4c3-4f16-807a-567800c9f41e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>fromFlightDate</value>
      <webElementGuid>3a851ed0-00e6-400a-aff4-07c2475d9074</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>92cb00f5-7a5d-44d4-ae99-e158d7498f2a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control custom-date </value>
      <webElementGuid>fd6e2c31-a6e4-4620-bf60-40697bee59c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;fromFlightDate&quot;)</value>
      <webElementGuid>b5cc57d6-ce53-4df7-bb8d-92c5d5e126ae</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='fromFlightDate']</value>
      <webElementGuid>98744134-ae7f-4576-b231-98cebf6d7e2d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//flight-schedule[@id='scflightschedule']/div/span/div/div/div/div/div[2]/div/div/div/div/input</value>
      <webElementGuid>f03e1c50-b502-42a7-99cf-75f59aecf8a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/div/div/div/div/div[2]/div/div/div/div/input</value>
      <webElementGuid>6382be57-ff36-4999-9ecd-5e7602c6d87f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'fromFlightDate' and @name = 'fromFlightDate']</value>
      <webElementGuid>282410ba-1578-4c56-85e4-6543fddf4c15</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
